CONFIG_LV_Z_MEM_POOL_SIZE=16384
CONFIG_LV_Z_SHELL=y
CONFIG_MAIN_STACK_SIZE=8192

CONFIG_DISPLAY=y
CONFIG_DISPLAY_LOG_LEVEL_INF=y

CONFIG_LOG=y
CONFIG_SHELL=y

#CONFIG_PM_DEVICE=y
#CONFIG_PM_DEVICE_RUNTIME=y

CONFIG_LVGL=y
#CONFIG_LV_MEM_CUSTOM=y
CONFIG_LV_USE_LOG=y
CONFIG_LV_USE_LABEL=y
#CONFIG_LV_USE_BTN=y
CONFIG_LV_USE_ARC=y
#CONFIG_LV_USE_IMG=y
CONFIG_LV_USE_MONKEY=y
CONFIG_LV_FONT_MONTSERRAT_16=y

# added for color display
CONFIG_LV_COLOR_16_SWAP=y
CONFIG_LV_COLOR_DEPTH_16=y

# added for input
CONFIG_LV_Z_POINTER_INPUT=y

#input pointer
CONFIG_LV_Z_POINTER_INPUT_MSGQ_COUNT=200

#added to get touch working
CONFIG_I2C=y
CONFIG_I2C_SHELL=y
CONFIG_SPI=y
CONFIG_INPUT=y
CONFIG_GPIO_SHELL=y
CONFIG_DEVICE_SHELL=y


# Test with polling
#CONFIG_INPUT_CST816S_INTERRUPT=y

CONFIG_LOGGING_SWIPES_ONLY=n
CONFIG_LOG_GESTURES_ONLY=n


#Gemini told me to add these
# Display Drivers
CONFIG_MIPI_DBI=y
CONFIG_ST7789V=y

# Touch Controller Driver
CONFIG_INPUT_CST816S=y
CONFIG_I2C_LOG_LEVEL_DBG=y
CONFIG_INPUT_LOG_LEVEL_DBG=y


CONFIG_PWM=y
CONFIG_LED=y
CONFIG_LED_PWM=y